app/models.py
from app.db import db


class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey("roles.id"))
    tickets = db.relationship("Ticket", backref="user")

    def __init__(self, username, role_id):
        self.username = username
        self.role_id = role_id

    def __repr__(self) -> str:
        return f"<User {self.usernmae}>"


class Role(db.Model):
    __tablename__ = "roles"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), unique=True)
    users = db.relationship("User", backref="role")

    def __init__(self, name):
        self.name = name

    def __repr__(self) -> str:
        return f"<Role {self.name}>"


class Client(db.Model):
    __tablename__ = "clients"
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(60))
    lastname = db.Column(db.String(60))
    nationality = db.Column(db.String(60))
    tickets = db.relationship("Ticket", backref="client")

    def __init__(self, firstname, lastname):
        self.firstname = firstname
        self.lastname = lastname

    def __repr__(self) -> str:
        return f"Client <{self.firstname} {self.lastname}>"


class Ticket(db.Model):
    ___tablename__ = "tickets"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    client_id = db.Column(db.Integer, db.ForeignKey("clients.id"))
    plan_id = db.Column(db.Integer, db.ForeignKey("plans.id"))

    def __init__(self, user_id, client_id, plan_id):
        self.user_id = user_id
        self.client__iid = client_id
        self.plan_id = plan_id

    def __repr__(self):
        return f"<Ticket {self.id}>"


class Plan(db.Model):
    __tablename__ = "plans"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    price = db.Column(db.Float())
    tickets = db.relationship("Ticket", backref="plan")

    def __init__(self, name, price):
        self.name = name
        self.price = price

    def __repr__(self) -> str:
        return f"<Plan {self.name}>"

app/forms.py
from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import StringField, DateTimeField, SubmitField
from wtforms.validators import DataRequired, Optional


def get_timestamp():
    return datetime.utcnow().timestamp()


class TicketForm(FlaskForm):
    author = StringField("Responsable", validators=[DataRequired()])
    client = StringField("Cliente", validators=[DataRequired()])
    plan_price = StringField("Plan", validators=[Optional()])
    submit = SubmitField("Guardar")

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from app.db import db
from app.views import crud


def create_app(test_config=None):
    app = Flask(__name__)
    app.config.from_object("app.config.DevelopmentConfig")

    db.init_app(app)
    Migrate(app, db)
    Bootstrap(app)

    return app


app = create_app()

# Blueprint register
app.register_blueprint(crud)

app/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.db import db
from app.forms import TicketForm
from app.models import Ticket

# import logging

# logging.basicConfig(
#     level=logging.INFO, filename="temp.log", format="{message}", style="{", filemode="w"
# )

crud = Blueprint("crud", __name__)


@crud.route("/")
def index_view():
    return render_template("index.html")


@crud.route("/list")
def list_view():
    tks = Ticket.query.all()
    return render_template("list.html", tks=tks)


@crud.route("/create", methods=["GET", "POST"])
def create_view():
    form = TicketForm()
    if form.validate_on_submit():
        new_record = Ticket(
            author=request.form["author"],
            client=request.form["client"],
            plan_price=request.form["plan_price"],
        )
        db.session.add(new_record)
        db.session.commit()

        flash("Registro añadido satisfactoriamente.")

        return redirect(url_for("crud.list_view"))

    return render_template("create.html", form=form)


# DELETE
@crud.route("/delete/<int:id>")
def delete_view(id):
    record = Ticket.query.get(id)
    db.session.delete(record)
    db.session.commit()
    flash("Registro eliminado.")
    return redirect(url_for("crud.list_view"))


@crud.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404


@crud.errorhandler(500)
def internal_server_error(e):
    return render_template("500.html"), 500

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta name="description" content="CRUD to register showers use in Uspallata"/>
        <meta name="keywords" content="KM1107 KM1151 Uspallata"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}"/>
        <link rel="stylesheet" href="{{ bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap') }}"/>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}"/>

        <title>
            {% block title %}Index{% endblock title %}
        </title>
    </head>

    <body>
        <header>
            {% block header %}
                {% include('partials/_navbar.html') %}
            {% endblock header %}
        </header>
        <main>
            <div class="contaner">
                {% block content %}
                {% endblock content %}
            </div>
        </main>
        <footer>
            {% block footer %}
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-info">
                            <button type="button" class="close" data-dismiss="alert">%times;</button>
                            {{ messages }}
                        </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            {% endblock footer %}
        </footer>
        {% block scripts %}
            <script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
            <script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
        {% endblock scripts %}
    </body>

</html>

app/templates/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Create{% endblock title %}

{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">Create New</div>
        </div>
        <div class="panel-body">
            {{ wtf.quick_form(form) }}

        {# 
            
            <form action="{{ url_for('crud.create_view') }}" method="post">
                {{ form.csrf_token }}
                {{ form.author.label }} {{ form.author(size=20) }}
                {{ form.client.label }} {{ form.client(size=20) }}
                {{ form.plan_price.label }} {{ form.plan_price(size=10) }}
                {{ form.submit }}
            </form>
        </div>
        #}
    </div>
{% endblock content %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Index</h1>
    <a href="{{ url_for('crud.list_view') }}">List...</a>
    <a href="{{ url_for('crud.create_view') }}">Create...</a>
{% endblock content %}

app/templates/list.html
{% extends "base.html" %}
{% block title %}List{% endblock title %}

{% block content %}
    <div>
        <table class="table">
            <tr>
                <th scope="col">TK</th>
                <th scope="col">Cliente</th>
                <th scope="col">Responsable</th>
                <th scope="col">Marca de Tiempo</th>
                <th scope="col">Acciones</th>
            </tr>
            {% for tk in tks %}
            <tr>
                <td>{{ tk.id }}</td>
                <td>{{ tk.client }}</td>
                <td>{{ tk.author }}</td>
                <td>{{ tk.timestamp }}</td>
                <td>
                    <a href="{{ url_for('crud.delete_view', id=tk.id) }}" class="small">delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

app/templates/partials/_navbar.html
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('crud.index_view' )}}">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('crud.list_view' )}}">Lista <span class="sr-only">(current)</span></a></li>
        <li><a href="{{ url_for('crud.create_view') }}">Nuevo</a></li>
        {# DROPDOWN
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        #}
      </ul>
      {# SEARCH FORM
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search"/>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      #}
      {# RIGHT LINKS
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
      #}
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/templates/update.html
{% extends "base.html" %}
{% block title %}Update{% endblock title %}

{% block content %}
    <form action="{{ url_for('crud.update_view', id=id) }}" method="post">
        {{ form.csrf_token }}
        {{ form.author.label }} {{ form.author(size=20) }}
        {{ form.client.label }} {{ form.client(size=20) }}
        {{ form.plan_price.label }} {{ form.plan_price(size=10) }}
        {{ form.submit }}
    </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%  %}</title>
</head>
<body>
    <main>
    {% block content%}
    {% endblock %}
    </main>
</body>
</html>